# Generated by Django 3.2.15 on 2022-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0002_auto_20221006_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='Time',
            field=models.IntegerField(null=True, verbose_name='Time'),
        ),
    ]
