# Generated by Django 3.2.15 on 2022-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0004_auto_20221006_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphy',
            fields=[
                ('id', models.IntegerField(help_text='primary key', primary_key=True, serialize=False)),
                ('Temperature1', models.IntegerField(verbose_name='Temperature')),
                ('Time2', models.IntegerField(verbose_name='Time')),
            ],
        ),
        migrations.DeleteModel(
            name='Graphs',
        ),
    ]
