# Generated by Django 3.2.15 on 2022-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0006_alter_graphy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature1', models.IntegerField(verbose_name='Temperature')),
                ('Time2', models.IntegerField(verbose_name='Time')),
            ],
        ),
        migrations.DeleteModel(
            name='Graphy',
        ),
    ]
