# Generated by Django 3.2.15 on 2022-10-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0010_auto_20221006_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.IntegerField(max_length=50)),
                ('Time', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Graphs',
        ),
    ]
