# Generated by Django 3.2.15 on 2022-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0011_auto_20221007_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='Temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temp',
            name='Time',
            field=models.IntegerField(),
        ),
    ]
