# Generated by Django 3.2.15 on 2022-10-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0012_auto_20221007_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('Gyro', models.IntegerField()),
                ('Current', models.IntegerField()),
                ('Time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
